version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jacky_tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/jacky_tracker
      PORT: 3001
      PGSSL: "false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "0.0.0.0:3001:3001"

volumes:
  db_data:


